/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload File */
        post: operations["upload_file_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capture/chatgpt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture Chatgpt Conversation */
        post: operations["capture_chatgpt_conversation_capture_chatgpt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_entities_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source
         * @description Poll extraction status for a specific source after upload.
         */
        get: operations["get_source_entities_sources__source_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Source
         * @description Delete a source, all its extracted entities (cascade), and the raw uploaded file.
         */
        delete: operations["delete_source_entities_sources__source_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/sources/{source_id}/reanalyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reanalyze Source
         * @description Wipe existing entities for a source and re-run extraction in the background.
         */
        post: operations["reanalyze_source_entities_sources__source_id__reanalyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decisions */
        get: operations["list_decisions_entities_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals */
        get: operations["list_goals_entities_goals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Constraints */
        get: operations["list_constraints_entities_constraints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/constraints/{constraint_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Constraint Status */
        patch: operations["update_constraint_status_entities_constraints__constraint_id__status_patch"];
        trace?: never;
    };
    "/entities/open-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Open Questions */
        get: operations["list_open_questions_entities_open_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/action-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Action Items */
        get: operations["list_action_items_entities_action_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Insights */
        get: operations["get_insights_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_settings_get"];
        put?: never;
        /**
         * Update Settings
         * @description Update API keys at runtime (in-memory; resets on server restart).
         *     For permanent storage add them as Replit Secrets.
         */
        post: operations["update_settings_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItemOut */
        ActionItemOut: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            status: components["schemas"]["ActionStatus"];
            /** Confidence */
            confidence: number;
            /** Source Reference */
            source_reference: string | null;
            /** Supporting Snippet */
            supporting_snippet: string | null;
        };
        /**
         * ActionStatus
         * @enum {string}
         */
        ActionStatus: "pending" | "done" | "cancelled" | "unknown";
        /** BehavioralNote */
        BehavioralNote: {
            /** Pattern */
            pattern: string;
            /** Source Filename */
            source_filename: string;
        };
        /** BlindSpot */
        BlindSpot: {
            /** Topic */
            topic: string;
            /** Discussion Count */
            discussion_count: number;
            /** Action Count */
            action_count: number;
            /** Ratio */
            ratio: number;
        };
        /** Body_upload_file_upload_post */
        Body_upload_file_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CaptureMessageIn */
        CaptureMessageIn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /** Content */
            content: string;
            /** Timestamp */
            timestamp?: string | null;
        };
        /** ChatGPTCaptureIn */
        ChatGPTCaptureIn: {
            /** Title */
            title?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Captured At */
            captured_at?: string | null;
            /** Messages */
            messages: components["schemas"]["CaptureMessageIn"][];
        };
        /** ConstraintOut */
        ConstraintOut: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Confidence */
            confidence: number;
            /** Source Reference */
            source_reference: string | null;
            /** Supporting Snippet */
            supporting_snippet: string | null;
            status?: components["schemas"]["ConstraintStatus"] | null;
        };
        /**
         * ConstraintStatus
         * @enum {string}
         */
        ConstraintStatus: "active" | "resolved";
        /** ConstraintStatusUpdate */
        ConstraintStatusUpdate: {
            status: components["schemas"]["ConstraintStatus"];
        };
        /** ConversationSourceOut */
        ConversationSourceOut: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Source Type */
            source_type: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Conversation Count */
            conversation_count: number;
            /** Extraction Status */
            extraction_status?: string | null;
            /** Provider Used */
            provider_used?: string | null;
            /** Entities Extracted */
            entities_extracted?: number | null;
            /** Extraction Confidence Avg */
            extraction_confidence_avg?: number | null;
            /** Extraction Duration Ms */
            extraction_duration_ms?: number | null;
        };
        /** DecisionOut */
        DecisionOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Timestamp */
            timestamp: string | null;
            /** Confidence */
            confidence: number;
            /** Source Reference */
            source_reference: string | null;
            /** Supporting Snippet */
            supporting_snippet: string | null;
            /** Source Id */
            source_id: number | null;
            /**
             * Reasons
             * @default []
             */
            reasons: components["schemas"]["ReasonOut"][];
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["EvidenceOut"][];
            /**
             * Outcomes
             * @default []
             */
            outcomes: components["schemas"]["OutcomeOut"][];
        };
        /** DecisionReversal */
        DecisionReversal: {
            original: components["schemas"]["DecisionOut"];
            reversal: components["schemas"]["DecisionOut"];
            /** Similarity */
            similarity: number;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Source Reference */
            source_reference: string | null;
        };
        /** FallbackStep */
        FallbackStep: {
            /** Provider */
            provider: string;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
        };
        /** GoalOut */
        GoalOut: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            status: components["schemas"]["GoalStatus"];
            /** Confidence */
            confidence: number;
            /** Source Reference */
            source_reference: string | null;
            /** Supporting Snippet */
            supporting_snippet: string | null;
            /** Timestamp */
            timestamp: string | null;
            /** Frequency */
            frequency: number;
        };
        /**
         * GoalStatus
         * @enum {string}
         */
        GoalStatus: "open" | "achieved" | "abandoned" | "unknown";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightReport */
        InsightReport: {
            /** Recurring Questions */
            recurring_questions: components["schemas"]["RecurringQuestionGroup"][];
            /** Decision Reversals */
            decision_reversals: components["schemas"]["DecisionReversal"][];
            /** Top Goals */
            top_goals: components["schemas"]["GoalOut"][];
            /** Blind Spots */
            blind_spots: components["schemas"]["BlindSpot"][];
            /**
             * Behavioral Notes
             * @default []
             */
            behavioral_notes: components["schemas"]["BehavioralNote"][];
            /** Total Decisions */
            total_decisions: number;
            /** Total Open Questions */
            total_open_questions: number;
            /** Total Action Items */
            total_action_items: number;
        };
        /** OpenQuestionOut */
        OpenQuestionOut: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Confidence */
            confidence: number;
            /** Source Reference */
            source_reference: string | null;
            /** Supporting Snippet */
            supporting_snippet: string | null;
        };
        /** OutcomeOut */
        OutcomeOut: {
            /** Id */
            id: number;
            /** Expected */
            expected: string;
            /** Actual */
            actual?: string | null;
            /** Confidence */
            confidence: number;
            /** Timeframe */
            timeframe?: string | null;
            /** Impact Statement */
            impact_statement?: string | null;
            /** Measured At */
            measured_at?: string | null;
        };
        /** ProviderStatus */
        ProviderStatus: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Configured */
            configured: boolean;
        };
        /** ReasonOut */
        ReasonOut: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Confidence */
            confidence: number;
        };
        /** RecurringQuestionGroup */
        RecurringQuestionGroup: {
            /** Representative */
            representative: string;
            /** Occurrences */
            occurrences: string[];
            /** Count */
            count: number;
        };
        /** SettingsOut */
        SettingsOut: {
            /** Providers */
            providers: components["schemas"]["ProviderStatus"][];
            /**
             * Heuristic Always Available
             * @default true
             */
            heuristic_always_available: boolean;
            /**
             * Llm Enabled
             * @default false
             */
            llm_enabled: boolean;
        };
        /** UpdateKeysIn */
        UpdateKeysIn: {
            /** Anthropic Api Key */
            anthropic_api_key?: string | null;
            /** Gemini Api Key */
            gemini_api_key?: string | null;
            /** Cerebras Api Key */
            cerebras_api_key?: string | null;
            /** Groq Api Key */
            groq_api_key?: string | null;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Source Id */
            source_id: number;
            /** Filename */
            filename: string;
            /** Source Type */
            source_type: string;
            /** Conversation Count */
            conversation_count: number;
            /** Entities Extracted */
            entities_extracted: number;
            /** Provider Used */
            provider_used?: string | null;
            /** Extraction Status */
            extraction_status?: string | null;
            /** Extraction Confidence Avg */
            extraction_confidence_avg?: number | null;
            /** Extraction Duration Ms */
            extraction_duration_ms?: number | null;
            /**
             * Fallback Chain
             * @default []
             */
            fallback_chain: components["schemas"]["FallbackStep"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_file_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_chatgpt_conversation_capture_chatgpt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatGPTCaptureIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_entities_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSourceOut"][];
                };
            };
        };
    };
    get_source_entities_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_entities_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reanalyze_source_entities_sources__source_id__reanalyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_entities_decisions_get: {
        parameters: {
            query?: {
                source_id?: number | null;
                min_confidence?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_entities_goals_get: {
        parameters: {
            query?: {
                source_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_constraints_entities_constraints_get: {
        parameters: {
            query?: {
                source_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstraintOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_constraint_status_entities_constraints__constraint_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                constraint_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConstraintStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstraintOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_open_questions_entities_open_questions_get: {
        parameters: {
            query?: {
                source_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenQuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_action_items_entities_action_items_get: {
        parameters: {
            query?: {
                source_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_insights_insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightReport"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_settings_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateKeysIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
